#!/bin/bash

[[ -z $ELASTIC_PORT ]] && exit 1
[[ -z $ELASTIC_URL  ]] && exit 1

data_file="$1"

[[ -z $data_file ]] && data_file=sample_data.csv

cat "$data_file" | grep -v '^#' \
| while read line
  do
    id=$(echo $line | cut -d';' -f1)
    location=$(echo $line | cut -d';' -f4)
    description=$(echo $line | cut -d';' -f5-)
    cat <<EOF
{"index":{"_index":"ads","_type":"immo","_id":"${id}"}}
{"location":"${location}","description":"${description}"}
EOF
  done \
| curl -XPOST $ELASTIC_URL/_bulk --data-binary @-

